# Generated by Django 2.0.6 on 2018-07-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20180716_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('required', models.BooleanField(verbose_name='Required')),
                ('type', models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)')], default='text', max_length=200, verbose_name='Type')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='myApp.Survey', verbose_name='Survey')),
            ],
        ),
    ]
