# Generated by Django 2.0.6 on 2018-07-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20180716_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='interview_uuid',
        ),
    ]
