# Generated by Django 2.0.6 on 2018-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20180717_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
