# Generated by Django 2.0.6 on 2018-07-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20180717_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'คำตอบยาว'), ('short-text', 'คำตอบสั้น')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
