# Generated by Django 2.0.6 on 2018-07-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20180727_1313'),
        ('myApp', '0011_response_user'),
    ]

    operations = [
    ]
