# Generated by Django 2.0.6 on 2018-07-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_merge_20180727_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'คำตอบยาว'), ('short-text', 'คำตอบสั้น')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
