# Generated by Django 2.0.6 on 2018-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20180727_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AddField(
            model_name='survey',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template'),
        ),
    ]
