# Generated by Django 2.0.6 on 2018-07-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_auto_20180727_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='template',
        ),
    ]
