# Generated by Django 2.0.6 on 2018-07-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_auto_20180727_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
