# Generated by Django 2.0.6 on 2018-08-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_auto_20180728_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text (คำตอบยาว)'), ('short-text', 'Short text (คำตอบสั้น)'), ('radio', 'Choices (คำตอบแบบสเกล)')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
